version: '3.8'

services:

  template_server:
    build: .
    ports:
      - 7861:7861
    environment:
      - PORT=7861
      - HOST=0.0.0.0
      - WORKERS=1
      - TIMEOUT=120
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB_NAME=template_db

  mongo:
    image: mongo
  