version: '3.8'

services:

  template_server:
    image: dmaichem/chem_templates_server
    # build: .
    ports:
      - ${TEMPLATE_SERVER_PORT}:${TEMPLATE_SERVER_PORT}
    env_file: .env

  mongo:
    image: mongo
